import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { GetPicturesResults, Pictures } from '../types'

const Home: NextPage<{pictures: Pictures[]}> = ({pictures}) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {pictures.map((picture) => {
        return <div key={picture.id}>
          {picture.pic_name}
        </div>
      })}
    </div>
  )
}

export const getStaticProps: GetStaticProps = async (context) => {
  const res = await fetch("https://api.airtable.com/v0/appuCYu7mTj0F3vQD/pictures", {
    headers: {
      Authorization: `Bearer ${process.env.AIRTABLE_API_TOKEN}`,
    },
  }).then((data) => {
    console.log(data)
    return data.json
  })


  // const {result}: GetPicturesResults = data
  // console.log(data)
  return {
    props: {
      pictures: result
    }
  }
}

export default Home
